// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/CloudStriver/platform-relation/biz/adaptor"
	"github.com/CloudStriver/platform-relation/biz/application/service"
	"github.com/CloudStriver/platform-relation/biz/infrastructure/config"
	"github.com/CloudStriver/platform-relation/biz/infrastructure/mapper/relation"
	"github.com/CloudStriver/platform-relation/biz/infrastructure/stores/redis"
)

// Injectors from wire.go:

func NewRelationServerImpl() (*adaptor.RelationServerImpl, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	redisRedis := redis.NewRedis(configConfig)
	relationNeo4jMapper := relation.NewNeo4jMapper(configConfig)
	relationServiceImpl := &service.RelationServiceImpl{
		Config:        configConfig,
		Redis:         redisRedis,
		RelationModel: relationNeo4jMapper,
	}
	relationServerImpl := &adaptor.RelationServerImpl{
		Config:          configConfig,
		RelationService: relationServiceImpl,
	}
	return relationServerImpl, nil
}
